Performance report tests
membraneframework/membrane_performance_test pull request #1
Opened 2022-02-23 09:12 UTC by varsill

Test can be launched with the mix task command:
`mix performance_test`
`--mode <push|pull|autodemand> `
`--n <number of elements in the pipeline>`
`--howManyTries <how many test runs will be performed> `
`--tick <single test run length [ms]> `
`--initialGeneratorFrequency <frequency of the message generator in the first run [msg/s]>`
`--statistics <comma separated list of statistic names which should be saved to the result file> `
`--reductions <number of reductions to be performed in each filter, while processing buffer>`
`OPTIONAL: [--shouldAdjustGeneratorFrequency, --shouldProducePlots, --shouldProvideStatisticsHeader]`
`ARG: <output directory path>` 

As a result, a csv file called `stats.csv` will be produced in the *output directory path*, containing the desired metrics. If `--shouldProvideStatisticsHeader` flag is defined, the chosen statistics names header will be present on the top of the result file.  If `--shouldProducePlots` optional flag is defined, in that directory there will also appear `*_plot.svg` files, with **MessagePassingTime(TimeWhenTheMessageWasSent)** plots.
Available statistics: `throughput, generator_frequency, passing_time_avg, passing_time_std, tick, tries_counter`

If `--shouldAdjustGeneratorFrequency` flag is set, the binary search of the optimal message generation frequency will be performed.

Some exemplary tests, defined inside the `boot_script.sh` file, can be launched within the docker environment, by:
1) `mkdir results` inside the root project directory
2) Building the image: `docker build -t performance_test .` inside the root project directory
3) Running the container: ``docker run -v `pwd`/results:/project/results/ performance_test`` inside the root project directory

2022-03-08 11:57 UTC, andpodob requested changes

2022-03-08 11:57 UTC, andpodob commented on config/config.exs
> +#   auto_migrate?: true # decides if the auto migration task should get triggered during supervisor initialization
We shouldn't leave commented code.

2022-03-08 11:57 UTC, andpodob commented on lib/AutoDemand/Sink.ex
> +    actions = actions ++ [demand: {:input, 1}]
Is auto demand sink required to output `:demand` action?

2022-03-08 11:57 UTC, andpodob commented on lib/AutoDemand/Sink.ex
> +    demand_unit: :buffers
Why do you define `demand_mode` explicitly like in `lib/AutoDemand/Filter.ex` and sometimes implicitly like here? btw. in the auto_demand mode default one?

2022-03-08 11:57 UTC, andpodob commented on lib/Base/Filter.ex
> +        ]
We should provide some default I guess.

2022-03-08 11:57 UTC, andpodob commented on lib/Base/Sink.ex
> +            "Positive integer, describing number of ticks after which the message to count evaluate the throughput should be send"
something bad happened to that sentence "message to count evaluate" :D

2022-03-08 11:57 UTC, andpodob commented on lib/Base/Sink.ex
> +      passing_time_std > 10_000_000 and passing_time_std > 0.5 * passing_time_avg ->
this deserves a comment (especially that this values were experimentally deduced)

2022-03-08 11:57 UTC, andpodob commented on lib/Base/Sink.ex
> +      try_no == 0 ->
let's move this check out of `check_nomrality`

2022-03-08 11:57 UTC, andpodob commented on lib/Base/Sink.ex
> +      |> Enum.map(fn key -> {key, Utils.access_nested_map(state, key)} end)
you should be able to use this: https://hexdocs.pm/bunch/Bunch.Access.html#get_in/2 here.

2022-03-08 11:57 UTC, andpodob commented on lib/Base/Source.ex
> +    {{:ok, start_timer: {:next_buffer_timer, Ratio.new(Time.milliseconds(@interval), 1)}}, state}
is the `Ratio` needed here?

2022-03-08 11:57 UTC, andpodob commented on lib/Base/Source.ex
> +          do: %Buffer{payload: @message, dts: Membrane.Time.monotonic_time()}
IMO PTS should be used here. DTS is specific for video compressed in a particular way, PTS fits better to pretty much everything else.

2022-03-08 11:57 UTC, andpodob commented on lib/Reductions.ex
> +  def calculate do
Shouldn't this be private? It relies on some module attributes, actually, it calculates some parameters of a particular function defined in this module (`:erlang.date()`). I would change this function to private if it's not used anywhere else or pass a function that is examined as an argument (you can set a default to `:erlang.date()`).

2022-03-08 11:57 UTC, andpodob commented on lib/Reductions.ex
> +    {_a, _b, r1, r2} = calculate()
it seems this `calculate()` is used only in this module, and only in this place (if my project scope search has not failed xdd), so it could return `{r1, r2}` if `a, b` turned out to be redundant.

2022-03-08 11:57 UTC, andpodob commented on lib/Task.ex
> +      [output_directory_path] = arguments
I believe we should provide some defaults, writing a command with so many arguments is a nightmare :D

2022-03-08 11:57 UTC, andpodob commented on mix.exs
>    end
I can't comment a code that was not added in this PR, but above in line 9 it shouldn't be `app: :membrane_template_plugin,`

2022-03-09 10:13 UTC, varsill commented on config/config.exs
> +#   auto_migrate?: true # decides if the auto migration task should get triggered during supervisor initialization
indeed - it concerns the usage of the dashboard, but I do not think we will take advantage of the dashboard anymore. I will remove all the dependencies concerning the dashboard

2022-03-09 11:06 UTC, varsill commented on config/config.exs
> +#   auto_migrate?: true # decides if the auto migration task should get triggered during supervisor initialization
done

2022-03-09 11:12 UTC, varsill commented on lib/AutoDemand/Sink.ex
> +    actions = actions ++ [demand: {:input, 1}]
As far as I know autodemands work only in filter elements

2022-03-09 11:14 UTC, varsill commented on lib/AutoDemand/Sink.ex
> +    demand_unit: :buffers
I believe only in filter elements we can choose the `:autodemand` or `:manual` options, according to what documentation says: https://github.com/membraneframework/membrane_core/blob/f55f6ed6a88fbe7d25689fdea26cc9e481c45b0e/lib/membrane/pad.ex#L67 and to the examples of pipelines using autodemands mechanism

2022-03-10 08:12 UTC, varsill commented on lib/Base/Sink.ex
> +            "Positive integer, describing number of ticks after which the message to count evaluate the throughput should be send"
indeed haha 
done

2022-03-10 08:50 UTC, varsill commented on lib/Base/Sink.ex
> +      try_no == 0 ->
done

2022-03-10 08:52 UTC, varsill commented on lib/Base/Sink.ex
> +      passing_time_std > 10_000_000 and passing_time_std > 0.5 * passing_time_avg ->
done

2022-03-10 08:53 UTC, varsill commented on lib/Base/Source.ex
> +          do: %Buffer{payload: @message, dts: Membrane.Time.monotonic_time()}
done

2022-03-10 08:56 UTC, varsill commented on lib/Reductions.ex
> +    {_a, _b, r1, r2} = calculate()
indeed, these are some leftovers after the development part. I have also slightly changed the variables names there.
done

2022-03-10 08:56 UTC, varsill commented on lib/Task.ex
> +      [output_directory_path] = arguments
I did so :D

2022-03-10 08:57 UTC, varsill commented on mix.exs
>    end
done

2022-03-10 08:59 UTC, varsill commented on lib/Reductions.ex
> +  def calculate do
I believe making it private is a better solution.
done

2022-03-10 09:49 UTC, varsill commented on lib/Base/Filter.ex
> +        ]
I will put the defaults just in the mix task implementation

2022-03-10 09:49 UTC, varsill commented on lib/Base/Source.ex
> +    {{:ok, start_timer: {:next_buffer_timer, Ratio.new(Time.milliseconds(@interval), 1)}}, state}
Probably it is not :D I removed it

2022-03-10 10:47 UTC, varsill commented on lib/Base/Sink.ex
> +      |> Enum.map(fn key -> {key, Utils.access_nested_map(state, key)} end)
and in fact I am, thanks :D done

2022-03-10 15:12 UTC, andpodob requested changes
Looks good, only the command-line interface requires some instruction in README and maybe some tweaking...

2022-03-10 15:12 UTC, andpodob commented on lib/Task.ex
> +   --shouldAdjustGeneratorFrequency, --shouldProducePlots, --shouldProvidemetricsHeader]
I was unsure how to use these flags. Either lets add possible values set or maybe it is possible to pass a flag without arguments, it is sometimes done like that right. I mean, one has to pass `--shouldProducePlots` instead of `--shouldProducePlots true`
```suggestion
   --shouldAdjustGeneratorFrequency, --shouldProducePlots <true|false>, --shouldProvidemetricsHeader]
```

2022-03-10 15:12 UTC, andpodob commented on lib/Task.ex
> +   --chosenMetrics <comma separated list of statistic names which should be saved, default: ''> --reductions <number of reductions to be performed in each filter, while processing buffer, default: 10
hmm... how to use `--chosenMetrics` what are the possible values?

2022-03-10 15:12 UTC, andpodob commented on lib/Task.ex
> +   --shouldAdjustGeneratorFrequency, --shouldProducePlots, --shouldProvidemetricsHeader]
I just give it a try and found out that this is a path to file where plots should be saved? Definitely, it was not clear to me :P

2022-03-10 15:12 UTC, andpodob commented on README.md
> +# Membrane Performance Test
README definitely requires an update, it should contain quite detailed instructions on how to use that tool.

2022-03-10 15:12 UTC, andpodob commented on lib/Task.ex
> +   --shouldAdjustGeneratorFrequency, --shouldProducePlots, --shouldProvidemetricsHeader]
<img width="1014" alt="image" src="https://user-images.githubusercontent.com/27630111/157678112-0e32760d-71c6-43af-816e-13bcc7ddafb4.png">

2022-03-14 12:36 UTC, varsill commented on lib/Task.ex
> +   --shouldAdjustGeneratorFrequency, --shouldProducePlots, --shouldProvidemetricsHeader]
When it comes to --should* flags, they do not require `true`|`false` values - you can just pass `--shouldAdjustGeneratorFrequency` and it will work just as if you have passed `--shouldAdjustGeneratorFrequency true`

2022-03-14 12:37 UTC, varsill commented on lib/Task.ex
> +   --shouldAdjustGeneratorFrequency, --shouldProducePlots, --shouldProvidemetricsHeader]
the other problem you have mentioned is already solved by creating the missing directories :P

2022-03-14 12:37 UTC, varsill commented on lib/Task.ex
> +   --chosenMetrics <comma separated list of statistic names which should be saved, default: ''> --reductions <number of reductions to be performed in each filter, while processing buffer, default: 10
done

2022-03-14 13:18 UTC, varsill commented on README.md
> +# Membrane Performance Test
done

2022-03-17 11:07 UTC, andpodob approved these changes

2022-03-17 11:07 UTC, andpodob commented on lib/AutoDemand/Sink.ex
> +    demand_unit: :buffers
ah, sorry, my bad!

2022-03-17 11:07 UTC, andpodob commented on lib/Base/Source.ex
> +    {{:ok, start_timer: {:next_buffer_timer, Ratio.new(Time.milliseconds(@interval), 1)}}, state}
Seems like it is still there :D

2022-03-17 11:44 UTC, andpodob requested changes
Some progress info while the test is being executed would be really welcome!

2022-03-17 11:44 UTC, andpodob commented on boot_script.sh
> +    mix performance_test --mode autodemand --numberOfElements 30 --howManyTries 3 --tick 10000 --reductions 1000 --initalGeneratorFrequency $((2500*$ITER)) --chosenMetrics passing_time_avg,passing_ti
```suggestion
    mix performance_test --mode autodemand --numberOfElements 30 --howManyTries 3 --tick 10000 --reductions 1000 --initalGeneratorFrequency $((2500*$ITER)) --chosenMetrics passing_time_avg,passing_time_std,throughput --shouldAdjustGeneratorFrequency --shouldProducePlots --shouldProvideMetricsHeader ./project/results/
```
btw. test still breaks when the path does not exist

2022-03-17 11:44 UTC, andpodob commented on lib/Task.ex
> +      File.mkdir(output_directory_path)
This is not creating directories recursively.

2022-03-18 08:48 UTC, varsill commented on boot_script.sh
> +    mix performance_test --mode autodemand --numberOfElements 30 --howManyTries 3 --tick 10000 --reductions 1000 --initalGeneratorFrequency $((2500*$ITER)) --chosenMetrics passing_time_avg,passing_ti
Indeed, `mkdir_p` should deal with it :P

2022-03-18 08:49 UTC, varsill commented on lib/Task.ex
> +      File.mkdir(output_directory_path)
done

2022-04-07 09:16 UTC, merged